#!/bin/sh

export XDG_CONFIG_HOME='./test/xdg/config/'
export XDG_STATE_HOME='./test/xdg/local/state/'
export XDG_DATA_HOME='./test/xdg/local/share/'

mkdir -p ${XDG_DATA_HOME}nvim/site/pack/testing/start/
ln -s $(pwd) ${XDG_DATA_HOME}nvim/site/pack/testing/start/copilot.lua
nvim --cmd 'set loadplugins' -l $@
exit_code=$?
rm ${XDG_DATA_HOME}nvim/site/pack/testing/start/copilot.lua

exit $exit_code
